### PR TITLE
Improved English syntax

### PR DESCRIPTION
**Pull request by edoreld**

### CODE REVIEW

**Review by oliviercailloux — CHANGES_REQUESTED** [review]
Thanks. I’d rather leave "code smells" as-is as it is a common phrase in XP. I’ll change the other one.

**Comment by edoreld** [comment]
Interesting, I wasn't familiar with this expression. I have added another commit that adds "code smells" back in (Not sure if there was a better way to do it).

P.S. in hindsight, I should have opened a new branch for the epf file changes

**Review by oliviercailloux — COMMENTED** [review]
My aim is different. The current phrasing and link also permit to download the raw file (through the 'Raw' button). It takes two steps instead of one, but OTOH it allows the reader to easily see the content of the file, a functionality which I want to keep.
And I want my users (who follow my course) to know about the "Raw" download button, that they are supposed to use to d/l the slides anyway.

**Comment by edoreld** [comment]
Fair enough. I have reverted the epf changes and kept the desired syntax improvements.

**Pull request merged**
